version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules


#Detailed Documentation:
#1. Specified the Docker Compose file version.
#2. Configured the services to run as containers.