apiVersion: v1

kind: Service
metadata:
  name: web-application

spec:
  type: NodePort
  selector:
    app: web-application
  ports:
    - port: 80
      targetPort: 3000


#Detailed Documentation:
#1. Specified the API version.
#2. Defined the kind "Service" and named it "web-application".
#3. Configured the selector to match the "web-application" app and map the ports.